### ISSUE TITLE
Missing packages in Arch Linux image (was: arch linux container mirror error)

### ISSUE THREAD

**Issue by tazihad** [toolbx-images/images#79] opened 2023-05-11 06:43 UTC
### Image and version of the image where the issue happens

archlinux

### Describe the bug

I can't enter archlinux container with distrobox. It's probably a mirror error. I can't get pass the step of `distrobox enter arch`.
```
distrobox enter arch
Container arch is not running.
Starting container arch
run this command to follow along:

 podman logs -f arch

 Starting container...                           [ OK ]
 Installing basic packages...                    Error: An error occurred
```

I tried with vpn. Still doesn't work.
if I see the logs `podman logs -f arch`. I get this error.
```
Total Download Size:    51.64 MiB
Total Installed Size:  250.04 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
warning: dependency cycle detected:
warning: libglvnd will be installed before its mesa dependency
 llvm-libs-15.0.7-3-x86_64 downloading...
 mesa-23.0.3-1-x86_64 downloading...
 vulkan-intel-23.0.3-1-x86_64 downloading...
 vulkan-radeon-23.0.3-1-x86_64 downloading...
 libglvnd-1.6.0-1-x86_64 downloading...
error: failed retrieving file 'libglvnd-1.6.0-1-x86_64.pkg.tar.zst.sig' from geo.mirror.pkgbuild.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'vulkan-intel-23.0.3-1-x86_64.pkg.tar.zst.sig' from geo.mirror.pkgbuild.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'vulkan-radeon-23.0.3-1-x86_64.pkg.tar.zst.sig' from geo.mirror.pkgbuild.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: too many errors from geo.mirror.pkgbuild.com, skipping for the remainder of this transaction
error: failed retrieving file 'llvm-libs-15.0.7-3-x86_64.pkg.tar.zst.sig' from geo.mirror.pkgbuild.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred

```

### Reproduction steps

```
distrobox create --name arch --image quay.io/toolbx-images/archlinux-toolbox:latest
distrobox enter arch
```

### Host distribution and version, toolbx and podman versions

Fedora silverblue 38
toolbox version 0.0.99.4
podman version 4.5.0

**Comment by travier** [comment] 2023-05-11 10:12
Looks like those packages should be added to https://github.com/toolbx-images/images/blob/main/archlinux/extra-packages

**Comment by Foxboron** [comment] 2023-05-11 10:21
@travier I think this is another issue.

**Comment by jelly** [comment] 2023-05-11 13:08
> Looks like those packages should be added to https://github.com/toolbx-images/images/blob/main/archlinux/extra-packages

It seems to be an issue with the default mirror from the toolbox container image.

I don't think the toolbox image should add more tools to the image https://github.com/89luca89/distrobox/blob/f008b521ee776a66c36a87848c85d3e3f0f6a3dd/distrobox-init#L551

**Comment by travier** [comment] 2023-05-15 09:24
Upstream toolbox images now include vulkan-drivers pacakges: https://github.com/containers/toolbox/blob/main/images/fedora/f38/extra-packages#L23

Those will be installed by distrobox on first setup time: https://github.com/89luca89/distrobox/blob/f008b521ee776a66c36a87848c85d3e3f0f6a3dd/distrobox-init#L589

We should included those in the image directly instead.

There might indeed be two issues here, one with the mirrors, one with the missing pacakges.

**Comment by Foxboron** [comment] 2023-05-15 09:31
>Upstream toolbox images now include vulkan-drivers packages:

Okay, I can submit a patch to include this into our images.

**Comment by travier** [comment] 2023-10-23 16:03
I don't think this has been fixed yet.

**Comment by travier** [comment] 2024-01-18 12:01
Closing as we'll soon withdraw the Arch Linux images in favor of the upstream ones from the toolbx project: https://github.com/toolbx-images/images/pull/82

If you can reproduce this issue with those images, please file an issue there. Thanks.

**Closed by travier** 2024-01-18 12:01 UTC
Labels: enhancement
